### PR TITLE
test with github actions on modern python&django versions

### PR DESCRIPTION
**Pull request by eviljeff**
https://github.com/eviljeff/nobot/actions/runs/704759975 in case this doesn't show up

### CODE REVIEW

**Comment by eviljeff** [comment]
@EnTeQuAk r? 😉

**Review by EnTeQuAk — APPROVED** [review]

**Comment by EnTeQuAk** [comment]
@eviljeff do you need to be released soon after merging? That I can do latest by Tuesday.

**Comment by eviljeff** [comment]
there's no rush really - there aren't any code changes (so far) just proof that tests pass on django3.2, which is good enough.

**Comment by eviljeff** [comment]
@EnTeQuAk I found this 😄 - if it's still valid can it be merged?

**Pull request closed without merging**
